main: main.cpp
	g++ -Wall main.cpp render.cpp util.cpp uds.cpp fifo.cpp study.cpp document.cpp message_parser.cpp imagePanel.cpp particle.cpp path_game.cpp -lpthread -lSDL2 -lSDL2_gfx -lSDL2_ttf -lSDL2_image -o sdl_frontend

debug: main.cpp
	g++ -g -Wall main.cpp render.cpp util.cpp uds.cpp fifo.cpp study.cpp document.cpp message_parser.cpp imagePanel.cpp particle.cpp path_game.cpp -lpthread -lSDL2 -lSDL2_gfx -lSDL2_ttf -lSDL2_image -o sdl_frontend
